name: dasboard_kit_with_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  flutter_svg: 1.1.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/img/
    - assets/icon/
  uses-material-design: true

